# Site settings
title: "[zy] zachyordy"
header-img: img/header.jpg
email: site-admin@zach.zachyordy.com
copyright_name: zachyordy
description: "[zy] zachyordy blog. A blog about the internet and technology."
#baseurl: "/startbootstrap-clean-blog-jekyll"
baseurl: ""
url: "http://blog.zachyordy.com"
facebook_username: zachyordy
twitter_username: zachyordy
#github_username:  davidtmiller
email_username:  site-admin@zach.zachyordy.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Added by ZJSY
host: 0.0.0.0
port: 58378
